name: makit_test_task
description: Test task

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  flutter_svg: ^1.1.5
  flutter_screenutil: ^5.5.4
  http: ^0.13.5
  meta: ^1.8.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0
  formz: ^0.4.1
  equatable: ^2.0.5
  flutter_gen: ^5.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
